"""database constants"""

# question_answer table
QA_CSV_HEADER_ID = "ID"
QA_CSV_HEADER_QUESTION = "Question"
QA_CSV_HEADER_ANSWER = "Answer"
QA_CSV_HEADER_VOTE_STATUS = "Vote Status"
QA_CSV_HEADER_TIMESTAMPS = "Timestamp"
QA_CSV_HEADER = (
    QA_CSV_HEADER_ID,
    QA_CSV_HEADER_QUESTION,
    QA_CSV_HEADER_ANSWER,
    QA_CSV_HEADER_VOTE_STATUS,
    QA_CSV_HEADER_TIMESTAMPS,
)

# ranking table
RANKING_CSV_HEADER_ID = "ID"
RANKING_CSV_HEADER_QUESTION = "Question"
RANKING_CSV_HEADER_UP_RANKING_ANSWER = "Up Ranking Answer"
RANKING_CSV_HEADER_LOW_RANKING_ANSWER = "Low Ranking Answer"
RANKING_CSV_HEADER = (
    RANKING_CSV_HEADER_ID,
    RANKING_CSV_HEADER_QUESTION,
    RANKING_CSV_HEADER_UP_RANKING_ANSWER,
    RANKING_CSV_HEADER_LOW_RANKING_ANSWER,
)

# RAG table
RAG_CSV_HEADER_ID = "ID"
RAG_CSV_HEADER_QUESTION = "Question"
RAG_CSV_HEADER_ANSWER = "Answer"
RAG_CSV_HEADER_EDITED = "Edited Answer"
RAG_CSV_HEADER_VOTE_STATUS = "Vote Status"
RAG_CSV_HEADER_RAG_SOURCES = "RAG Sources"
RAG_CSV_HEADER_SOURCE = "Source"
RAG_CSV_HEADER_SOURCE_CONTENT = "Source Content"
RAG_CSV_HEADER_TIMESTAMP = "Timestamp"
RAG_CSV_HEADER = (
    RAG_CSV_HEADER_ID,
    RAG_CSV_HEADER_QUESTION,
    RAG_CSV_HEADER_ANSWER,
    RAG_CSV_HEADER_EDITED,
    RAG_CSV_HEADER_VOTE_STATUS,
    RAG_CSV_HEADER_RAG_SOURCES,
    RAG_CSV_HEADER_SOURCE,
    RAG_CSV_HEADER_SOURCE_CONTENT,
    RAG_CSV_HEADER_TIMESTAMP,
)

# list separator
RAG_LIST_SEPARATOR = "||"

# Comparator table
COMPARATOR_CSV_HEADER_ID = "ID"
COMPARATOR_CSV_HEADER_MODEL = "Model"
COMPARATOR_CSV_HEADER_QID = "Question ID"
COMPARATOR_CSV_HEADER_QUESTION = "Question"
COMPARATOR_CSV_HEADER_ANSWER = "Answer"
COMPARATOR_CSV_HEADER_RANK = "Rank"
COMPARATOR_CSV_HEADER_TIMESTAMP = "Timestamp"
COMPARATOR_CSV_HEADER = (
    COMPARATOR_CSV_HEADER_ID,
    COMPARATOR_CSV_HEADER_MODEL,
    COMPARATOR_CSV_HEADER_QID,
    COMPARATOR_CSV_HEADER_QUESTION,
    COMPARATOR_CSV_HEADER_ANSWER,
    COMPARATOR_CSV_HEADER_RANK,
    COMPARATOR_CSV_HEADER_TIMESTAMP,
)
