"""database constants"""

# question_answer table
QA_CSV_HEADER_ID = 'ID'
QA_CSV_HEADER_QUESTION = 'Question'
QA_CSV_HEADER_ANSWER = 'Answer'
QA_CSV_HEADER_VOTE_STATUS = 'Vote Status'
QA_CSV_HEADER_TIMESTAMPS = 'Timestamp'
QA_CSV_HEADER = (
    QA_CSV_HEADER_ID,
    QA_CSV_HEADER_QUESTION,
    QA_CSV_HEADER_ANSWER,
    QA_CSV_HEADER_VOTE_STATUS,
    QA_CSV_HEADER_TIMESTAMPS
)

# ranking table
CSV_HEADER_ID = "ID"
CSV_HEADER_QUESTION = "Question"
RANKING_CSV_HEADER_UP_RANKING_ANSWER = "Up Ranking Answer"
RANKING_CSV_HEADER_LOW_RANKING_ANSWER = "Low Ranking Answer"
RANKING_CSV_HEADER = (
    CSV_HEADER_ID,
    CSV_HEADER_QUESTION,
    RANKING_CSV_HEADER_UP_RANKING_ANSWER,
    RANKING_CSV_HEADER_LOW_RANKING_ANSWER,
)
