export const dataold = [
  { epoch: 1, error: 77.19, change: 0, "time (s)": 100 },
  { epoch: 2, error: 77.83, change: 0.34, "time (s)": 100 },
  { epoch: 3, error: 76.24, change: 0.24, "time (s)": 100 },
  { epoch: 4, error: 75.44, change: -0.14, "time (s)": 100 },
  { epoch: 5, error: 67.51, change: 0.14, "time (s)": 100 },
  { epoch: 6, error: 57.1, change: 0.08, "time (s)": 100 },
  { epoch: 7, error: 56.91, change: 0.08, "time (s)": 100 },
  { epoch: 8, error: 47.53, change: 0.04, "time (s)": 100 },
  { epoch: 9, error: 47.47, change: 0.04, "time (s)": 100 },
  { epoch: 10, error: 23.48, change: 0.041, "time (s)": 100 },
  { epoch: 11, error: 18.03, change: 0.04, "time (s)": 100 },
  { epoch: 12, error: 17.23, change: 0.033, "time (s)": 100 },
  { epoch: 13, error: 16.54, change: 0.002, "time (s)": 100 },
  { epoch: 14, error: 7.54, change: -0.04, "time (s)": 100 },
  { epoch: 15, error: 6.5, change: 0.01, "time (s)": 100 },
  { epoch: 16, error: 7.18, change: 0.011, "time (s)": 100 },
  { epoch: 17, error: 6.12, change: 0.012, "time (s)": 100 },
  { epoch: 18, error: 7.87, change: 0.04, "time (s)": 100 },
  { epoch: 19, error: 6.73, change: 0.04, "time (s)": 100 },
  { epoch: 20, error: 6.55, change: 0.04, "time (s)": 100 },
  { epoch: 21, error: 6.23, change: 0.04, "time (s)": 100 },
  { epoch: 22, error: 6.31, change: 0.04, "time (s)": 100 },
  { epoch: 23, error: 6.74, change: 0.04, "time (s)": 100 },
  { epoch: 24, error: 5.95, change: 0.04, "time (s)": 100 },
  { epoch: 25, error: 4.92, change: 0.04, "time (s)": 100 },
  { epoch: 26, error: 4.61, change: 0.04, "time (s)": 100 },
  { epoch: 27, error: 3.62, change: 0.004, "time (s)": 100 },
  { epoch: 28, error: 5.35, change: 0.004, "time (s)": 100 },
  { epoch: 29, error: 5.28, change: 0.0004, "time (s)": 100 },
];

export const comparisonData = [
  { model: "llama", qid: 1, rank: 1, answer: "Llama's first unique answer." },
  {
    model: "gpt3.5",
    qid: 1,
    rank: 2,
    answer: "GPT-3.5's first unique answer.",
  },
  { model: "gpt4", qid: 1, rank: 3, answer: "GPT-4's first unique answer." },
  { model: "claude", qid: 1, rank: 4, answer: "Claude's first unique answer." },

  { model: "llama", qid: 2, rank: 2, answer: "Llama's second unique answer." },
  {
    model: "gpt3.5",
    qid: 2,
    rank: 1,
    answer: "GPT-3.5's second unique answer.",
  },
  { model: "gpt4", qid: 2, rank: 4, answer: "GPT-4's second unique answer." },
  {
    model: "claude",
    qid: 2,
    rank: 3,
    answer: "Claude's second unique answer.",
  },

  { model: "llama", qid: 3, rank: 3, answer: "Llama's third unique answer." },
  {
    model: "gpt3.5",
    qid: 3,
    rank: 4,
    answer: "GPT-3.5's third unique answer.",
  },
  { model: "gpt4", qid: 3, rank: 1, answer: "GPT-4's third unique answer." },
  { model: "claude", qid: 3, rank: 2, answer: "Claude's third unique answer." },

  { model: "llama", qid: 4, rank: 4, answer: "Llama's fourth unique answer." },
  {
    model: "gpt3.5",
    qid: 4,
    rank: 3,
    answer: "GPT-3.5's fourth unique answer.",
  },
  { model: "gpt4", qid: 4, rank: 2, answer: "GPT-4's fourth unique answer." },
  {
    model: "claude",
    qid: 4,
    rank: 1,
    answer: "Claude's fourth unique answer.",
  },

  { model: "llama", qid: 5, rank: 4, answer: "Llama's fifth unique answer." },
  {
    model: "gpt3.5",
    qid: 5,
    rank: 2,
    answer: "GPT-3.5's fifth unique answer.",
  },
  { model: "gpt4", qid: 5, rank: 3, answer: "GPT-4's fifth unique answer." },
  { model: "claude", qid: 5, rank: 1, answer: "Claude's fifth unique answer." },

  { model: "llama", qid: 6, rank: 2, answer: "Llama's sixth unique answer." },
  {
    model: "gpt3.5",
    qid: 6,
    rank: 1,
    answer: "GPT-3.5's sixth unique answer.",
  },
  { model: "gpt4", qid: 6, rank: 4, answer: "GPT-4's sixth unique answer." },
  { model: "claude", qid: 6, rank: 3, answer: "Claude's sixth unique answer." },

  { model: "llama", qid: 7, rank: 3, answer: "Llama's seventh unique answer." },
  {
    model: "gpt3.5",
    qid: 7,
    rank: 4,
    answer: "GPT-3.5's seventh unique answer.",
  },
  { model: "gpt4", qid: 7, rank: 1, answer: "GPT-4's seventh unique answer." },
  {
    model: "claude",
    qid: 7,
    rank: 2,
    answer: "Claude's seventh unique answer.",
  },

  { model: "llama", qid: 8, rank: 4, answer: "Llama's eighth unique answer." },
  {
    model: "gpt3.5",
    qid: 8,
    rank: 3,
    answer: "GPT-3.5's eighth unique answer.",
  },
  { model: "gpt4", qid: 8, rank: 2, answer: "GPT-4's eighth unique answer." },
  {
    model: "claude",
    qid: 8,
    rank: 1,
    answer: "Claude's eighth unique answer.",
  },
];

export const data = [
  { model: "llama", qid: 1, rank: 1, answer: "Llama's first unique answer." },
  {
    model: "gpt3.5",
    qid: 1,
    rank: 2,
    answer: "GPT-3.5's first unique answer.",
  },
  { model: "gpt4", qid: 1, rank: 3, answer: "GPT-4's first unique answer." },
  { model: "claude", qid: 1, rank: 4, answer: "Claude's first unique answer." },

  { model: "llama", qid: 2, rank: 4, answer: "Llama's second unique answer." },
  {
    model: "gpt3.5",
    qid: 2,
    rank: 2,
    answer: "GPT-3.5's second unique answer.",
  },
  { model: "gpt4", qid: 2, rank: 4, answer: "GPT-4's second unique answer." },
  { model: "claude", qid: 2, rank: 3, answer: "'s second unique answer." },

  { model: "llama", qid: 3, rank: 1, answer: "Llama's third unique answer." },
  {
    model: "gpt3.5",
    qid: 3,
    rank: 4,
    answer: "GPT-3.5's third unique answer.",
  },
  { model: "gpt4", qid: 3, rank: 4, answer: "GPT-4's third unique answer." },
  { model: "claude", qid: 3, rank: 2, answer: "'s third unique answer." },

  { model: "llama", qid: 4, rank: 1, answer: "Llama's fourth unique answer." },
  { model: "gpt3.5", qid: 4, rank: 3, answer: "GPT-3.5's  unique answer." },
  { model: "gpt4", qid: 4, rank: 2, answer: "GPT-4's  unique answer." },
  { model: "claude", qid: 4, rank: 4, answer: "'s  unique answer." },

  { model: "llama", qid: 5, rank: 1, answer: "Llama's  unique answer." },
  { model: "gpt3.5", qid: 5, rank: 2, answer: "GPT-3.5's nique answer." },
  { model: "gpt4", qid: 5, rank: 3, answer: "GPT-4's fifth unique answer." },
  { model: "claude", qid: 5, rank: 4, answer: "'s fifthnswer." },

  { model: "llama", qid: 6, rank: 1, answer: "Llama's sixth unique answer." },
  {
    model: "gpt3.5",
    qid: 6,
    rank: 2,
    answer: "GPT-3.5's sixth unique answer.",
  },
  { model: "gpt4", qid: 6, rank: 3, answer: "GPT-4's sixth unique answer." },
  { model: "claude", qid: 6, rank: 4, answer: "'s sixth uniq." },
  { model: "llama", qid: 7, rank: 4, answer: "Llama's seventh unique answer." },
  {
    model: "gpt3.5",
    qid: 7,
    rank: 3,
    answer: "GPT-3.5's seventh unique answer.",
  },
  { model: "gpt4", qid: 7, rank: 2, answer: "GPT-4's seventh unique answer." },
  {
    model: "claude",
    qid: 7,
    rank: 1,
    answer: "Claude's seventh unique answer.",
  },

  { model: "llama", qid: 8, rank: 3, answer: "Llama's eighth unique answer." },
  {
    model: "gpt3.5",
    qid: 8,
    rank: 4,
    answer: "GPT-3.5's eighth unique answer.",
  },
  { model: "gpt4", qid: 8, rank: 1, answer: "GPT-4's eighth unique answer." },
  {
    model: "claude",
    qid: 8,
    rank: 2,
    answer: "Claude's eighth unique answer.",
  },

  { model: "llama", qid: 9, rank: 2, answer: "Llama's ninth unique answer." },
  {
    model: "gpt3.5",
    qid: 9,
    rank: 1,
    answer: "GPT-3.5's ninth unique answer.",
  },
  { model: "gpt4", qid: 9, rank: 4, answer: "GPT-4's ninth unique answer." },
  { model: "claude", qid: 9, rank: 3, answer: "Claude's ninth unique answer." },

  { model: "llama", qid: 10, rank: 4, answer: "Llama's tenth unique answer." },
  {
    model: "gpt3.5",
    qid: 10,
    rank: 3,
    answer: "GPT-3.5's tenth unique answer.",
  },
  { model: "gpt4", qid: 10, rank: 2, answer: "GPT-4's tenth unique answer." },
  {
    model: "claude",
    qid: 10,
    rank: 1,
    answer: "Claude's tenth unique answer.",
  },

  {
    model: "llama",
    qid: 11,
    rank: 3,
    answer: "Llama's eleventh unique answer.",
  },
  {
    model: "gpt3.5",
    qid: 11,
    rank: 4,
    answer: "GPT-3.5's eleventh unique answer.",
  },
  {
    model: "gpt4",
    qid: 11,
    rank: 1,
    answer: "GPT-4's eleventh unique answer.",
  },
  {
    model: "claude",
    qid: 11,
    rank: 2,
    answer: "Claude's eleventh unique answer.",
  },

  {
    model: "llama",
    qid: 12,
    rank: 2,
    answer: "Llama's twelfth unique answer.",
  },
  {
    model: "gpt3.5",
    qid: 12,
    rank: 1,
    answer: "GPT-3.5's twelfth unique answer.",
  },
  { model: "gpt4", qid: 12, rank: 4, answer: "GPT-4's twelfth unique answer." },
  {
    model: "claude",
    qid: 12,
    rank: 3,
    answer: "Claude's twelfth unique answer.",
  },

  {
    model: "llama",
    qid: 13,
    rank: 4,
    answer: "Llama's thirteenth unique answer.",
  },
  {
    model: "gpt3.5",
    qid: 13,
    rank: 3,
    answer: "GPT-3.5's thirteenth unique answer.",
  },
  {
    model: "gpt4",
    qid: 13,
    rank: 2,
    answer: "GPT-4's thirteenth unique answer.",
  },
  {
    model: "claude",
    qid: 13,
    rank: 4,
    answer: "Claude's thirteenth unique answer.",
  },

  {
    model: "llama",
    qid: 14,
    rank: 3,
    answer: "Llama's fourteenth unique answer.",
  },
  {
    model: "gpt3.5",
    qid: 14,
    rank: 1,
    answer: "GPT-3.5's fourteenth unique answer.",
  },
  {
    model: "gpt4",
    qid: 14,
    rank: 1,
    answer: "GPT-4's fourteenth unique answer.",
  },
  {
    model: "claude",
    qid: 14,
    rank: 1,
    answer: "Claude's fourteenth unique answer.",
  },
];
